# Generated by Django 3.2 on 2023-04-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='net_name',
            field=models.CharField(default='105871', max_length=24),
        ),
    ]
